/**
 * Turns the Inkscape export in resources/door.svg into src/ui/door.svg.
 *
 *   node scripts/clean-door.mjs
 *
 * The geometry is copied verbatim — paths, transforms and clip paths are left
 * exactly as drawn. Only the packaging changes:
 *
 *   - the embedded ICC profile goes (it is ~1 MB of the 1.06 MB file)
 *   - Inkscape/sodipodi namespaces and editor metadata go
 *   - the painted yellow becomes `currentColor`, so CSS drives the panel and
 *     the solved badge turns green with a single property
 *   - the printed black becomes the cellar background, so the lines read as
 *     gaps cut out of the panel rather than as ink on top of it
 *
 * Re-run this if the artwork is ever redrawn.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import { rmSync } from 'node:fs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = resolve(root, 'resources/door.svg');
const OUT = resolve(root, 'src/ui/door.svg');
const META = resolve(root, 'src/ui/door.meta.js');

const PANEL = '#feed54'; // the printed yellow
const INK = '#010101'; // the printed black

// the export is CMYK and carries a stray byte or two; latin1 keeps it lossless
let svg = readFileSync(SRC, 'latin1');

svg = svg
  // the ICC profile and the editor's own bookkeeping
  .replace(/<color-profile[\s\S]*?\/>/g, '')
  .replace(/<metadata[\s\S]*?<\/metadata>/g, '')
  .replace(/<!--[\s\S]*?-->/g, '')
  .replace(/<\?xml[^>]*\?>/g, '')
  // editor-only *elements*, not just attributes: leaving <sodipodi:namedview>
  // behind after dropping its namespace makes the whole file unparseable
  .replace(/<(inkscape|sodipodi):([\w-]+)[\s\S]*?<\/\1:\2>/g, '')
  .replace(/<(?:inkscape|sodipodi):[\w-]+[^>]*\/>/g, '')
  .replace(/\s(?:inkscape|sodipodi):[\w-]+="[^"]*"/g, '')
  .replace(/\sxmlns:(?:inkscape|sodipodi|xlink|svg)="[^"]*"/g, '')
  .replace(/\sid="(?:svg|defs|layer)[\w-]*"/g, '')
  // recolour
  .replaceAll(`fill:${PANEL}`, 'fill:currentColor')
  .replaceAll(`stroke:${INK}`, 'stroke:var(--door-ink, #100c0b)')
  // the outer <svg> gets its size from CSS, not from the print dimensions
  .replace(/\swidth="[^"]*"/, '')
  .replace(/\sheight="[^"]*"/, '')
  // collapse the attribute-per-line formatting
  .replace(/\s*\n\s*/g, ' ')
  .replace(/\s{2,}/g, ' ')
  .replace(/> </g, '><')
  .trim();

const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1];
if (!viewBox) throw new Error('No viewBox survived the cleanup — check the source.');

/* Fail loudly rather than shipping a file the browser will refuse to parse.
   A namespace prefix left behind after its xmlns declaration was stripped is
   an "unbound prefix" error, and the app renders Chromium's parser-error page
   instead of the door. */
const declared = new Set(
  [...svg.matchAll(/xmlns:([\w-]+)="/g)].map((m) => m[1]).concat(['xml'])
);
const used = new Set(
  [...svg.matchAll(/<\/?([\w-]+):/g)].map((m) => m[1]).concat(
    [...svg.matchAll(/\s([\w-]+):[\w-]+="/g)].map((m) => m[1])
  )
);
const unbound = [...used].filter((p) => !declared.has(p) && p !== 'xmlns');
if (unbound.length) {
  throw new Error(`Unbound namespace prefixes left in the output: ${unbound.join(', ')}`);
}

/* The export came off a business card, where the door bled past the card
   crop, so the original viewBox clips the top of the arch. Measure what the
   artwork actually occupies and fit the viewBox to that. Doing it in a real
   renderer rather than by parsing path data keeps it correct through the
   transforms and clip paths the export is full of. */
const bbox = measureContent(svg);
const fitted = `${bbox.x.toFixed(3)} ${bbox.y.toFixed(3)} ${bbox.w.toFixed(3)} ${bbox.h.toFixed(3)}`;
svg = svg.replace(/viewBox="[^"]*"/, `viewBox="${fitted}"`);

writeFileSync(OUT, `${svg}\n`, 'utf8');
writeFileSync(
  META,
  `// Generated by scripts/clean-door.mjs — do not edit.\n` +
    `export const DOOR_VIEWBOX = { w: ${bbox.w.toFixed(3)}, h: ${bbox.h.toFixed(3)} };\n`,
  'utf8'
);

console.log(`wrote src/ui/door.svg`);
console.log(`  viewBox ${viewBox}  ->  ${fitted}`);
console.log(`  ${(readFileSync(SRC).length / 1024).toFixed(0)} KB -> ${(svg.length / 1024).toFixed(1)} KB`);

/**
 * Renders the markup in headless Chromium and reads back the union bounding
 * box of everything drawn, in user units. `stroke: true` matters — half of
 * this artwork is stroked lines that stick out past their path geometry.
 */
function measureContent(markup) {
  const browser = ['chromium', 'chromium-browser', 'google-chrome'].find((candidate) => {
    try {
      execFileSync(candidate, ['--version'], { stdio: 'ignore' });
      return true;
    } catch {
      return false;
    }
  });
  if (!browser) throw new Error('No Chromium/Chrome on PATH — needed to measure the artwork.');

  // snap-confined Chromium cannot read /tmp, so stage the file inside the repo
  const tmp = resolve(root, 'src/ui/.measure.html');
  writeFileSync(
    tmp,
    `<!doctype html><meta charset="utf-8"><body>${markup}<script>
      const el = document.querySelector('svg');
      const b = el.getBBox({ stroke: true, fill: true, markers: true });
      document.body.textContent = JSON.stringify({ x: b.x, y: b.y, w: b.width, h: b.height });
    </script>`
  );

  const dom = execFileSync(
    browser,
    ['--headless', '--disable-gpu', '--virtual-time-budget=4000', '--dump-dom', tmp],
    { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }
  );
  rmSync(tmp);

  const json = dom.match(/\{"x":[^}]*\}/)?.[0];
  if (!json) throw new Error('Could not measure the artwork — Chromium returned no bbox.');

  const b = JSON.parse(json);
  // a hair of padding so the outermost stroke never lands on the edge
  const pad = Math.max(b.w, b.h) * 0.005;
  return { x: b.x - pad, y: b.y - pad, w: b.w + pad * 2, h: b.h + pad * 2 };
}
